kind: Service 
apiVersion: v1
metadata:
  name: forex-miner-heimdallr-connections-api
  namespace: forex-miner
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: forex-miner-heimdallr-connections-api