//----------------------------------------------------------------------------------------
// <copyright file="ForexMinerHeimdallrDbContext.cs" company="geriremenyi.com">
//     Author: Gergely Reményi
//     Copyright (c) geriremenyi.com. All rights reserved.
// </copyright>
//----------------------------------------------------------------------------------------

namespace ForexMiner.Heimdallr.Common.Data.Database.Context
{
    using ForexMiner.Heimdallr.Common.Data.Database.Models.Instrument;
    using ForexMiner.Heimdallr.Common.Data.Database.Models.User;
    using Microsoft.EntityFrameworkCore;
    using System.Diagnostics.CodeAnalysis;
    using ForexMiner.Heimdallr.Common.Data.Database.Models.Connection;
    using ForexMiner.Heimdallr.Common.Data.Database.Models.Trade;

    /// <summary>
    /// Database context of the forex-miner-heimdallr.
    /// 
    /// This contains the entire database shceme for all microservices
    /// implemented under forex-miner-heimdallr package.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class ForexMinerHeimdallrDbContext : DbContext
    {
        /// <summary>
        /// List of registered users in the application
        /// </summary>
        public DbSet<User> Users { get; set; }

        /// <summary>
        /// List of instruments defined tradeable by the application
        /// </summary>
        public DbSet<Instrument> Instruments { get; set; }

        /// <summary>
        /// List of connections created by the application users
        /// </summary>
        public DbSet<Connection> Connections { get; set; }

        /// <summary>
        /// Trade signals generated by the engine
        /// </summary>
        public DbSet<TradeSignal> TradeSignals { get; set; }

        /// <summary>
        /// Constructor of the ForexMinerHeimdallrDbContext
        /// </summary>
        /// <param name="options">Connection parameters</param>
        public ForexMinerHeimdallrDbContext(DbContextOptions<ForexMinerHeimdallrDbContext> options) : base(options) { 
        }

        /// <summary>
        /// On model creation
        /// Set up the connections between models
        /// </summary>
        /// <param name="modelBuilder">The model builder object</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Instrument and granularities relationship
            modelBuilder.Entity<Instrument>()
                .HasMany(instrument => instrument.Granularities)
                .WithOne(granularity => granularity.Instrument);

            // Connections and owners relationship
            modelBuilder.Entity<User>()
                .HasMany(user => user.Connections)
                .WithOne(connection => connection.Owner);
        }
    }
}
