version: '3.4'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: pfw3KXpLkDnE52ys
            ACCEPT_EULA: Y
    redis:
        image: redis:alpine
        command: redis-server --requirepass JHG35TNgRSt6j3CB
        ports:
            - 6379:6379
        volumes:
            - $PWD/redis-data:/var/lib/redis
            - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master
    #forexminer.heimdallr.configurationmanager:
    #    image: ${DOCKER_REGISTRY-}forexminer.heimdallr.configurationmanager
    #    ports:
    #        - 32010:80
    #    build:
    #        context: .
    #        dockerfile: ConfigurationManager/Dockerfile
    forex-miner-heimdallr-user-api:
       image: ${DOCKER_REGISTRY-}forex-miner-heimdallr-user-api
       build:
            context: .
            dockerfile: /Dockerfile