version: '3.4'

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server
        environment:
            SA_PASSWORD: pfw3KXpLkDnE52ys
            ACCEPT_EULA: Y
    forexminer.heimdallr.usermanager:
        image: ${DOCKER_REGISTRY-}forexminerheimdallrusermanager
        build:
            context: .
            dockerfile: ForexMiner.Heimdallr.UserManager/Dockerfile
        depends_on:
            - sqlserver