name: Common.Data Continuous Integration
on: [pull_request]
jobs:
  build:
    name: Build Common.Data
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Common/Common.Data/Common.Data.csproj
  test:
    name: Test Common.Data
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Common/Common.Data.Tests/Common.Data.Tests.csproj