name: Common.Caching Continuous Integration
on: [pull_request]
jobs:
  build:
    name: Build Common.Caching
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Common/Common.Caching/Common.Caching.csproj
  test:
    name: Test Common.Caching
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Common/Common.Caching.Tests/Common.Caching.Tests.csproj