name: Connections.Secret Continuous Integration
on: [pull_request]
jobs:
  connections-secret-build:
    name: Build Connections.Secret
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Connections/Connections.Secret/Connections.Secret.csproj
  connections-secret-test:
    name: Test Connections.Secret
    runs-on: ubuntu-latest
    needs: [connections-secret-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Connections/Connections.Secret.Tests/Connections.Secret.Tests.csproj