name: Connections.Worker Continuous Integration
on: [pull_request]
jobs:
  connections-worker-build:
    name: Build Connections.Worker
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Connections/Connections.Worker/Connections.Worker.csproj
  connections-worker-test:
    name: Test Connections.Worker
    runs-on: ubuntu-latest
    needs: [connections-worker-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Connections/Connections.Worker.Tests/Connections.Worker.Tests.csproj
  connections-worker-docker-build:
    name: Docker build Connections.Worker
    runs-on: ubuntu-latest
    needs: [connections-worker-build, connections-worker-test]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Connections/Connections.Worker/Dockerfile
          push: false