name: Connections.Api Continuous Integration
on: [pull_request]
jobs:
  connections-api-build:
    name: Build Connections.Api
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Connections/Connections.Api/Connections.Api.csproj
  connections-api-test:
    name: Test Connections.Api
    runs-on: ubuntu-latest
    needs: [connections-api-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Connections/Connections.Api.Tests/Connections.Api.Tests.csproj
  connections-api-docker-build:
    name: Docker build Connections.Api
    runs-on: ubuntu-latest
    needs: [connections-api-build, connections-api-test]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Connections/Connections.Api/Dockerfile
          push: false