name: Instruments.Storage Continuous Integration
on: [pull_request]
jobs:
  instruments-storage-build:
    name: Build Instruments.Storage
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Instruments/Instruments.Storage/Instruments.Storage.csproj
  instruments-storage-test:
    name: Test Instruments.Storage
    runs-on: ubuntu-latest
    needs: [instruments-storage-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Instruments/Instruments.Storage.Tests/Instruments.Storage.Tests.csproj