name: Instruments.Api Continuous Integration
on: [pull_request]
jobs:
  instruments-api-build:
    name: Build Instruments.Api
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Instruments/Instruments.Api/Instruments.Api.csproj
  instruments-api-test:
    name: Test  Instruments.Api
    runs-on: ubuntu-latest
    needs: [instruments-api-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Instruments/Instruments.Api.Tests/Instruments.Api.Tests.csproj
  instruments-api-docker-build:
    name: Docker build Instruments.Api
    runs-on: ubuntu-latest
    needs: [instruments-api-build, instruments-api-test]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Instruments/Instruments.Api/Dockerfile
          push: false