name: Instruments.Worker Continuous Deployment
on:
  push:
    branches:
      - master
jobs:
  instruments-worker-build:
    name: Build Instruments.Worker
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Instruments/Instruments.Worker/Instruments.Worker.csproj
  instruments-worker-test:
    name: Test Instruments.Worker
    runs-on: ubuntu-latest
    needs: [instruments-worker-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Instruments/Instruments.Worker.Tests/Instruments.Worker.Tests.csproj
  instruments-worker-release:
    name: Tag and release Instruments.Worker
    runs-on: ubuntu-latest
    needs: [instruments-worker-build, instruments-worker-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version
        id: package-version
        run: echo "::set-output name=current-version::$(./scripts/get_version.sh ./src/Instruments/Instruments.Worker/Instruments.Worker.csproj)"

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Instruments/Instruments.Worker/Dockerfile
          push: true
          tags: |
            ghcr.io/geriremenyi/forex-miner-heimdallr-instruments-worker:${{ steps.package-version.outputs.current-version }}
            ghcr.io/geriremenyi/forex-miner-heimdallr-instruments-worker:latest

  instruments-worker-deploy:
    name: Deploy Instruments.Worker
    needs: [instruments-worker-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout IaaC
        uses: actions/checkout@v2
        with:
          repository: geriremenyi/forex-miner-asgard
          ref: master
          path: forex-miner-asgard
          token: ${{ secrets.GH_PAT }}

      - name: Connect to AKS
        working-directory: forex-miner-asgard
        shell: pwsh
        run: |
          ./init.ps1 -ApplicationId "${{ secrets.AZURE_APPLICATION_ID }}" -Secret "${{ secrets.AZURE_SECRET }}" -Tenant "${{ secrets.AZURE_TENANT }}"
          Connect-AKSCluster
      - name: Deploy to AKS
        shell: pwsh
        working-directory: forex-miner-asgard
        run: |
          ./init.ps1
          kubectl create secret docker-registry ghcr-secret --namespace=forex-miner --docker-server=https://ghcr.io/ --docker-username=notneeded --docker-password=${{ secrets.GH_PAT }}
          Deploy-KubernetesResource -ResourceYamlFileName 'app.yaml' -ResourceFolder '../src/Instruments/Instruments.Worker/Kubernetes'