name: Users.Api Continuous Deployment
on: [pull_request]   
#  push:
#    branches:
#      - master
jobs:
  users-api-build:
    name: Build Users.Api
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build
        run: dotnet build ./src/Users/Users.Api/Users.Api.csproj
  users-api-test:
    name: Test Users.Api
    runs-on: ubuntu-latest
    needs: [users-api-build]
    steps:
      - name: Setup .NET Core 3.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Test
        run: dotnet test ./src/Users/Users.Api.Tests/Users.Api.Tests.csproj
  users-api-release:
    name: Tag and release Users.Api
    runs-on: ubuntu-latest
    needs: [users-api-build, users-api-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get version
        id: package-version
        run: |
          echo "$(./scripts/get_version.sh ./src/Users/Users.Api.Tests/Users.Api.csproj)" 
          echo "::set-output name=current-version::$(./scripts/get_version.sh ./src/Users/Users.Api.Tests/Users.Api.csproj)"

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Users/Users.Api/Dockerfile
          push: true
          tags: |
            ghcr.io/geriremenyi/forex-miner-heimdallr-users-api:${{ steps.package-version.outputs.current-version }}
            ghcr.io/geriremenyi/forex-miner-heimdallr-users-api:latest

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: Users.Api-${{ steps.package-version.outputs.current-version}}
          draft: false
          prerelease: false

  users-api-deploy:
    name: Deploy
    needs: [users-api-release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout IaaC
        uses: actions/checkout@v2
        with:
          repository: geriremenyi/forex-miner-asgard
          ref: master
          path: forex-miner-asgard
          token: ${{ secrets.GH_PAT }}

      - name: Connect to AKS
        working-directory: forex-miner-asgard
        shell: pwsh
        run: |
          ./init.ps1 -ApplicationId "${{ secrets.AZURE_APPLICATION_ID }}" -Secret "${{ secrets.AZURE_SECRET }}" -Tenant "${{ secrets.AZURE_TENANT }}"
          Connect-AKSCluster
      - name: Deploy to AKS
        shell: pwsh
        working-directory: forex-miner-asgard
        run: |
          ./init.ps1
          kubectl create secret docker-registry ghcr-secret --namespace=forex-miner --docker-server=https://ghcr.io/ --docker-username=notneeded --docker-password=${{ secrets.GH_PAT }}
          Deploy-KubernetesResource -ResourceYamlFileName 'app.yaml' -ResourceFolder '../Users/Users.Api/Kubernetes'
          Deploy-KubernetesResource -ResourceYamlFileName 'service.yaml' -ResourceFolder '../Users/Users.Api/Kubernetes'